### ISSUE TITLE
OAI verb=Identify doesn't work on Islandora production server

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#50] opened 2016-03-09 21:17 UTC
From Mike Nov 20, 2015:

"FSU has the OAI module enabled and it seems to be working well with the exception of the Identify verb. For example, https://fsu.digital.flvc.org/oai2?verb=ListRecords&metadataPrefix=mods
appears to work just fine while https://fsu.digital.flvc.org/oai2?verb=Identify either times out or displays this:

XML Parsing Error: no element found
Location: https://fsu.digital.flvc.org/oai2?verb=Identify
Line Number 2, Column 315:<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd"><responseDate>2015-11-20T15:38:35Z</responseDate><request>http://fsu.digital.flvc.org/oai2</request>

It’s configuration is nearly identical on test and the same verb works fine: https://fsu-test.digital.flvc.org/oai2?verb=Identify
The only difference I see is that fsu-test has a larger maximum response size for records, but I don’t see how that would influence this example. There is also a difference between the solr configuration request handler (let solr decide vs standard) –I don’t know if this worth noting."

Lydia:
I’ve done some searching and haven’t seen and problem reports about this in the Islandora community.

I’ll note to check this after the upgrade on the production server.

NOTE:  
- verb=Identify works on the test server, and has worked on the test server under all releases, so this appears to be an issue that's independent of Islanodra release.
- I'm guessing that there's something specific to the production server that causes this problem.

**Comment by wrandtkeflvc** [comment] 2016-03-10 14:04
OAI-PMH verb Identify is working today on test sites, but not on production sites.

**Comment by glewisorg** [comment] 2016-03-10 15:09
I think the problem is the resource index query to get the earliestDateStamp value for the identify reply.  The select is sorting all objects in the entire repository by lastModifiedDate:

    $itql_query = 'select $object $date from <#ri>
                             where $object <info:fedora/fedora-system:def/model#label> $title
                             and $object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
                             and $object <info:fedora/fedora-system:def/view#lastModifiedDate> $date
                             order by $date asc';

It works on test because the repository on test is small.  Identify on any test site produces the same value:
`<earliestDatestamp>2012-05-10T14:26:56Z</earliestDatestamp>`

This resource index query is just bad and is never going to work on production.  I suggest that we switch it to use a Solr query.  Does it make sense to limit that query to a site rather than the entire repository?  It doesn't affect Solr response time, just wondering what is appropriate here.

**Comment by lydiam** [comment] 2016-03-10 15:14
I believe that it makes sense to limit to a site, at least from the perspective of Florida on Florida harvests.  (I’m working on moving the FoF harvests from DigiTool to Islandora, and it appears that those harvests are done by collection/site.)  At this point we just don’t know how the new discovery tool works.

**Comment by wrandtkeflvc** [comment] 2016-03-10 15:18
Gail,  That makes sense.  I think someone pulling an OAI-PMH feed from a university or college repository would expect info only on that one institution.  Your fix gets a more accurate value for the field (a bonus on top of working).

**Comment by wrandtkeflvc** [comment] 2017-09-13 20:08
I think this issue is fine to close.  When I run the identify request against different sites (for example, https://fau.digital.flvc.org/oai2?verb=Identify ), I get a valid response.  I'll bring up closing this ticket at the next developers meeting.

**Comment by wrandtkeflvc** [comment] 2017-09-14 17:03
Checked in at the FLVC Islandora Developers meeting, and this is fine to close per Lydia.

**Closed by wrandtkeflvc** 2017-09-14 17:03 UTC
